### PR TITLE
Few minor fixes, state of support for mona

### PR DESCRIPTION
**Pull request by wangray**
To run, put my [forked `mona.py`](https://github.com/wangray/mona) in the `plugins/x64dbgpy` folder, along with `pykd.py` and `x64dbgpylib.py`. 

Then, from the Python console, `import mona; mona.mona("command")`

State of support: https://github.com/x64dbg/x64dbgpylib/issues/5

### CODE REVIEW

**Comment by mrexodia** [comment]
Would be it easier if I gave you direct access to this repository?

**Comment by wangray** [comment]
@mrexodia It's probably better if you or someone else with more familiarity takes the lead. I just started working with Windows, x64dbg, and mona a few days ago. 

For instance, if I need changes to x64dbgpy, then I have no clue where to start. 

Maybe I can ask in the IRC or other x64dbg groups if others can help.

**Comment by wangray** [comment]
I am ok with merging this soon and starting to get community feedback. 

On second thought, if giving me write access helps mona stuff get fixed faster, then could you add me? 

Also, should I just place my `mona.py` in this repo or keep it separate on my fork? I plan to submit a PR to Corelan once mona is fully supported on x64dbg.

**Comment by mrexodia** [comment]
I invited you to the 'Python' team in the x64dbg organisation, as for `mona.py` feel free to do whatever you like. Perhaps it makes sense to add it here so users can test more easily but you know this better than me.

**Comment by wangray** [comment]
Ok, thanks. I think it makes sense to make a new mona repo in the x64dbg organization (since there seems to be quite a few other forks here). Can you transfer the mona repo if I've made you a collaborator @mrexodia ?

**Comment by mrexodia** [comment]
Alright, I transferred the repository and gave the python team access.

**Pull request merged**
