### PR TITLE
Preliminary dbgCommands support

### PR DESCRIPTION
**Pull request by jmreyes**
I've been working on the dbgCommands support, rough edges and weird things everywhere, but I thought I could drop it here in case it's useful for other contributors as a start. Feel free to suggest changes if this is something you'd like to merge.

### CODE REVIEW

**Comment by corelanc0d3r** [comment]
nice work :)  -  quick comment though - I don't think the idea is to build support for windbg commands, as those commands are only used in conjunction with windbglib.    mona.py is mostly using methods (immlib or the wrappers that I wrote in windbglib), so I believe the idea is to write the methods and use the native d64dbg api to produce the same output.  (not sure if that makes any sense)

**Comment by mrexodia** [comment]
@corelanc0d3r yes, but we use your `windbglib` as a basis and try to make mona.py work without modifying that before we can add the missing functionality from windbglib.

**Comment by mrexodia** [comment]
Thanks @jmreyes I merged it and gave you write access.

**Comment by jmreyes** [comment]
Thank you!

@corelanc0d3r what you say makes total sense, "support" is a bit unfortunate here, the idea is to produce the same output as pykd so that in turn windbglib directly generates correct output for mona.py... should be easy to refactor it to remove the need of pykd "emulation" once we have it working.

**Comment by corelanc0d3r** [comment]
okay got it, that makes sense ! :)

**Pull request merged**
